CREATE TABLE TB_COLABORADOR
(
    MATRICULA VARCHAR (10),
    CPF VARCHAR2(11),
    NOME VARCHAR2(100),
    SALARIO DECIMAL (6,2),
    ESTADO VARCHAR2(2),
    CIDADE VARCHAR2(50),
    BAIRRO VARCHAR2(50),
    LOGRADOURO VARCHAR2(150),
    COMPLEMENTO VARCHAR2(50),
    CEP VARCHAR2(8),
    DEPARTAMENTO VARCHAR (3)
)

CREATE TABLE TB_DEPARTAMENTO
( 
  SIGLA VARCHAR (3),
  NOME VARCHAR2(100),
  CHEFE VARCHAR2(100),
  DEPARTAMENTO_SUPERIOR VARCHAR(100)
)

CREATE TABLE TB_TELEFONE_COLABORADOR
( 
  COLABORADOR VARCHAR (10),
  NUMERO VARCHAR2(9),
  TIPO VARCHAR(1)
)

CREATE TABLE TB_EMAIL_COLABORADOR
( 
  EMAIL VARCHAR (50),
  COLABORADOR VARCHAR (10),
  TIPO VARCHAR(1)
)

CREATE TABLE TB_DEPENDENTE
( 
  CPF VARCHAR2(11),
  COLABORADOR VARCHAR (10),
  NOME VARCHAR2(100),
  DATA_DE_NASCIMENTO DATE,
  PARENTESCO VARCHAR(10)
)

CREATE TABLE TB_PROJETO
( 
  ID VARCHAR(10),
  NOME VARCHAR2(100),
  RESPONSAVEL VARCHAR(100),
  INICIO DATE,
  FIM DATE
)

CREATE TABLE TB_ATRIBUICAO
( 
  COLABORADOR VARCHAR (10),
  PROJETO VARCHAR2(100),
  PAPEL VARCHAR(100)
)

CREATE TABLE TB_PAPEL
( 
  ID VARCHAR(10),
  NOME VARCHAR2(100),
)

COMMIT

DROP TABLE TB_COLABORADOR;

DROP TABLE TB_DEPARTAMENTO;

DROP TABLE TB_TELEFONE_COLABORADOR;

DROP TABLE TB_EMAIL_COLABORADOR;

DROP TABLE TB_DEPENDENTE;

DROP TABLE TB_ATRIBUICAO;

DROP TABLE TB_PAPEL;